# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  #config.vm.provision "shell", path: "bootstrap.sh"
  #config.vm.provision "shell", path: "bootstrap_rs.sh"

  NodeCount = 2

  # Mongodb Worker Nodes
  (0..NodeCount).each do |i|
    config.vm.define "opsmongodb#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "opsmongodb#{i}.example.com"
      workernode.vm.network "private_network", ip: "172.17.20.10#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "opsmongodb#{i}"
        v.memory = 1024
        v.cpus = 1
        # Prevent VirtualBox from interfering with host audio stack
        v.customize ["modifyvm", :id, "--audio", "none"]
      end
      workernode.vm.provider :libvirt do |v|
        v.memory = 1048
        v.nested = true
        v.cpus = 1
      end
     # workernode.vm.provision "shell", path: "bootstrap_replset.sh"
    end
  end

  OpsNode = 1
  # MongoDB OpsManager  Node 
  (0..OpsNode).each do |i|
    config.vm.define "opsmanager" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "opsmanager#{i}.example.com"
      workernode.vm.network "private_network", ip: "172.16.201.10#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "opsmanager#{i}"
        v.memory = 6144 
        v.cpus = 2
        # Prevent VirtualBox from interfering with host audio stack
        v.customize ["modifyvm", :id, "--audio", "none"]
      end
      workernode.vm.provider :libvirt do |v|
        v.memory = 2048 
        v.nested = true
        v.cpus = 2
      end
      workernode.vm.provision "shell", path: "bootstrap_ops.sh"
    end
  end

end
